usr/include/mariadb/server
usr/include/mariadb/server/mysql
# usr/include/mariadb/server/mysql/client_plugin.h
# usr/include/mariadb/server/mysql/plugin_auth.h
# usr/include/mariadb/server/mysql/plugin_auth.h
# usr/include/mariadb/server/mysql/plugin_auth_common.h
# usr/include/mariadb/server/mysql_com.h
# usr/include/mariadb/server/mysql_version.h
# usr/include/mariadb/server/mysqld_error.h
usr/lib/*/libmariadbd.a
usr/lib/*/libmariadbd.so
usr/lib/*/libmysqld.a
usr/lib/*/libmysqld.so
usr/lib/*/pkgconfig/mariadb.pc
